import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:openfood_models/openfood_models.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../providers/cart_provider.dart';
import 'stripe_backend_service.dart';

class OrderService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Crée un document Order validé depuis le contenu du panier
  static Future<void> createOrder(
    CartProvider cart, {
    String? customerPhone,
    String? deliveryAddress,
    double? customerLat,
    double? customerLng,
    String? stripePaymentIntentId,
    String? promoCodeId,
    double? discountAmount,
  }) async {
    try {
      if (cart.items.isEmpty) return;

      // Extract details
      final firstItem = cart.items.values.first;
      final restaurantIdRaw = firstItem.restaurantId; // Ex: "Kay Dada · Lamentin"
      final restaurantName = restaurantIdRaw.split(' · ').first;
      
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) throw Exception("Utilisateur non connecté !");

      final userDoc = await _firestore.collection('users').doc(user.uid).get();
      final customerName = userDoc.exists ? userDoc.data()!['name'] as String? : user.displayName;

      final orderData = OrderModel(
        id: '', // Generated by Firestore
        userId: user.uid,
        restaurantId: restaurantIdRaw,
        restaurantName: restaurantName,
        status: 0, // 0 = En attente du restaurant
        totalAmount: cart.totalFinal,
        createdAt: DateTime.now(),
        items: cart.items.values.map((item) => {
          'id': item.id,
          'name': item.name,
          'quantity': item.quantity,
          'price': item.price,
          'priceHT': item.priceHT,
          'vatRate': item.vatRate,
          'selectedOptions': item.selectedOptions,
        }).toList(),
        customerPhone: customerPhone,
        customerName: customerName,
        deliveryAddress: deliveryAddress,
        customerLat: customerLat,
        customerLng: customerLng,
        stripePaymentIntentId: stripePaymentIntentId,
        promoCodeId: promoCodeId,
        discountAmount: discountAmount,
        paymentStatus: stripePaymentIntentId != null ? 'pending' : null,
      );

      await _firestore.runTransaction((transaction) async {
        if (promoCodeId != null) {
          final promoRef = _firestore.collection('promo_codes').doc(promoCodeId);
          final promoSnap = await transaction.get(promoRef);
          
          if (promoSnap.exists) {
            final promoData = promoSnap.data() as Map<String, dynamic>;
            final promo = PromoCodeModel.fromJson(promoData);
            
            if (!promo.isValid()) {
              throw Exception("Ce code promo n'est plus valide ou a atteint sa limite d'utilisation.");
            }
            
            transaction.update(promoRef, {
              'currentUses': FieldValue.increment(1),
            });
          }
        }
        
        final newOrderRef = _firestore.collection('orders').doc();
        // Since id is empty, we must ensure it's generated, but our model has id, we can set it to newOrderRef.id or just use .add which auto-generates.
        // Actually since we're using a transaction with .set(), we need to pass the generated id
        final finalOrderData = orderData.toMap();
        transaction.set(newOrderRef, finalOrderData);
      });

      debugPrint("🛒 Commande enregistrée avec succès dans Firestore.");
    } catch (e) {
      debugPrint("❌ Erreur sauvegarde commande: $e");
      throw Exception("Impossible d'enregistrer la commande dans la base de données.");
    }
  }

  /// Écoute en temps réel les commandes d'un utilisateur spécifique
  static Stream<List<OrderModel>> getUserOrdersStream() {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return const Stream.empty();

    return _firestore
        .collection('orders')
        .where('userId', isEqualTo: user.uid)
        .limit(100)
        .snapshots()
        .map((snapshot) {
      final orders = snapshot.docs.map((doc) => OrderModel.fromFirestore(doc)).toList();
      // Tri local anti-crash Firestore (évite la création d'Index composite Firebase manuel)
      orders.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return orders;
    });
  }

  /// Écoute en temps réel les commandes D'UN RESTAURANT
  static Stream<List<OrderModel>> getRestaurantOrdersStream(String restaurantId) {
    return _firestore
        .collection('orders')
        .where('restaurantId', isEqualTo: restaurantId)
        .limit(100)
        .snapshots()
        .map((snapshot) {
      final orders = snapshot.docs.map((doc) => OrderModel.fromFirestore(doc)).toList();
      orders.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return orders;
    });
  }

  /// (TEST/PILOTE) Récupère toutes les commandes sans filtrer par restaurant
  static Stream<List<OrderModel>> getAllOrdersStream() {
    return _firestore
        .collection('orders')
        .limit(100)
        .snapshots()
        .map((snapshot) {
      final orders = snapshot.docs.map((doc) => OrderModel.fromFirestore(doc)).toList();
      orders.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return orders;
    });
  }

  /// Met à jour le statut d'une commande
  static Future<void> updateOrderStatus(String orderId, int newStatus, [int? prepTimeMinutes]) async {
    try {
      // NOTE: Capture and cancel are now handled securely by Cloud Functions.
      if (newStatus == 1) {
        // Capture the payment when the restaurant accepts the order
        bool captured = await StripeBackendService.capturePaymentIntent(orderId);
        if (!captured) {
          debugPrint("Attention: Le paiement n'a pas pu être capturé. On continue l'update pour l'UI, mais vérifiez les logs.");
        }
      } else if (newStatus == 4) {
        // Cancel the payment authorization when the order is cancelled
        bool cancelled = await StripeBackendService.cancelPaymentIntent(orderId);
        if (!cancelled) {
          debugPrint("Attention: L'autorisation n'a pas pu être annulée. Vérifiez les logs Stripe.");
        }
      }

      final data = <String, dynamic>{'status': newStatus};
      if (newStatus == 3) {
        data['deliveredAt'] = Timestamp.now();
      }
      if (prepTimeMinutes != null) {
        data['prepTimeMinutes'] = prepTimeMinutes;
      }
      await _firestore.collection('orders').doc(orderId).update(data);
      debugPrint("✅ Statut de la commande mis à jour : $newStatus");
    } catch (e) {
      debugPrint("❌ Erreur mise à jour de la commande: $e");
      throw Exception("Impossible de mettre à jour le statut.");
    }
  }

  /// Écoute en temps réel les commandes PRÊTES (status == 2) et SANS LIVREUR
  static Stream<List<OrderModel>> getAvailableDeliveriesStream() {
    return _firestore
        .collection('orders')
        .where('status', isEqualTo: 2)
        .where('driverId', isNull: true) // Filtre de Firebase pour ramener les non-assignées.
        .limit(50)
        .snapshots()
        .map((snapshot) {
      final orders = snapshot.docs.map((doc) => OrderModel.fromFirestore(doc)).toList();
      orders.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return orders;
    });
  }

  /// Écoute en temps réel les commandes assignées au LIVREUR (status >= 3)
  static Stream<List<OrderModel>> getMyDeliveriesStream(String driverId) {
    return _firestore
        .collection('orders')
        .where('driverId', isEqualTo: driverId)
        .limit(50)
        .snapshots()
        .map((snapshot) {
      final orders = snapshot.docs.map((doc) => OrderModel.fromFirestore(doc)).toList();
      // Exclusion locale des terminées / annulées si besoin (ou on laisse pour un historique)
      orders.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      return orders;
    });
  }

  /// Le livreur accepte une course (assignation du driverId, statut passe à 3, ajout des infos livreur)
  static Future<void> assignDriver(String orderId, String driverId) async {
    try {
      // Récupérer les informations du livreur pour le restaurateur/client
      final user = FirebaseAuth.instance.currentUser;
      String? driverPhone = user?.phoneNumber;
      String? driverName = user?.displayName;
      
      // Fallback sur les SharedPreferences si FirebaseAuth ne les a pas
      if (driverPhone == null || driverPhone.isEmpty) {
        final prefs = await SharedPreferences.getInstance();
        driverPhone = prefs.getString('phoneNumber') ?? '0600000000';
      }
      if (driverName == null || driverName.isEmpty) {
        driverName = 'Livreur Partenaire';
      }

      await _firestore.collection('orders').doc(orderId).update({
        'driverId': driverId,
        'driverName': driverName,
        'driverPhone': driverPhone,
      });
      debugPrint("✅ Course acceptée par le livreur : $driverName ($driverPhone)");
    } catch (e) {
      debugPrint("❌ Erreur acceptation de course: $e");
      throw Exception("Impossible d'accepter la course.");
    }
  }
}
