// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA49Q5B4nF8K2OZtDoxUsmELpAb0zZUZbc',
    appId: '1:178517740611:web:09dfba077107c07f59d8f6',
    messagingSenderId: '178517740611',
    projectId: 'app-openfood',
    authDomain: 'app-openfood.firebaseapp.com',
    storageBucket: 'app-openfood.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7OZDdwQ98ahlONONb_LZTZjWISEWxGoY',
    appId: '1:178517740611:android:cfafa8d6ddf9e06759d8f6',
    messagingSenderId: '178517740611',
    projectId: 'app-openfood',
    storageBucket: 'app-openfood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJHJNtYBPBNAfo8yhzRnLOmT2nDCJEyE',
    appId: '1:178517740611:ios:c9f97d98c28246a859d8f6',
    messagingSenderId: '178517740611',
    projectId: 'app-openfood',
    storageBucket: 'app-openfood.firebasestorage.app',
    iosBundleId: 'com.openfood.app',
  );

}